#!/bin/sh
module="scull"
device="scull"
mode="664"
#invoke insmod with all arg we got
#and use a pathname, as newer modutils dont look in . by def
/sbin/insmod ./$module.ko $* || exit 1

#remove stales
rm -f /dev/${device}0
major=$(awk "\\$2==\"$module\" {print \\$1}" /proc/devices)
mknod /dev/${device}0 $major 0
chmod $mode /dev/${device}0

